- name: Create a VM from latest template
  hosts: localhost
  gather_facts: yes
  vars_files:
    - variable/variable.yml
  tasks:
  - name: Clone the template
    vmware_guest:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ VMWARE_USER }}"
      password: "{{ VMWARE_PASSWORD }}"
      validate_certs: False
      name: "{{ test_vm }}"
      template: "{{ vm_name_template }}"
      datacenter: "{{ vmware_datacenter }}"
      folder: "{{ vmware_folder }}"
      state: poweredon
      is_template: No
      cluster: "{{ vmware_cluster }}"
      wait_for_ip_address: yes
    register: vm_facts

  - name: get ip
    debug:
      msg: "{{ vm_facts.instance.ipv4 }} {{ test_vm }}"

  - name: Check for ping
    command: /usr/bin/ping -c 4 {{ vm_facts.instance.ipv4 }}
    register: ping_response

  - name: Check vm and power off
    command: /usr/bin/echo  "Server not pingable"
    when: ping_response.rc != 0

    command: /usr/bin/ansible-playbook power-off.yaml -e VMWARE_USER=$ENV_USER -e VMWARE_PASSWORD=$ENV_PASSWORD
    when: ping_response.rc == 0

  - name: Delete VM
    vmware_guest:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ VMWARE_USER }}"
      password: "{{ VMWARE_PASSWORD }}"
      validate_certs: False
      name: "{{ test_vm }}"
      template: "{{ vm_name_template }}"
      datacenter: "{{ vmware_datacenter }}"
      folder: "{{ vmware_folder }}"
      state: absent
      is_template: No
      cluster: "{{ vmware_cluster }}"

