pipelines:
   template-patching-prod-2k12:
    secure_variables:
      ENV_USR: "aes:afR1Jn+xAudF0/Nm2N2EG2N/baI/CDEvPQn+sBBr6SA="
      ENV_PAS: "aes:vYQVUN7yu95pKam/1zqY5Q=="
    group: Windows-Template-Patching
    timer:
      spec: "0 0 3 ? * SAT"
      only_on_changes: no
    materials:
      infracode:
        git: git@githuben.intranet.mckinsey.com:himanshu-sharma-xft/template-patching-prod-2k12.git
        branch: master
        auto_update: true
        blacklist:
        - "README.md"
    stages:
      - Update-Template:
          clean_workspace: true
          jobs:
            Update-Template:          
              resources:
                - linux
              tasks:
                - exec:
                    command: ansible-playbook -e "VMWARE_USER=$ENV_USR VMWARE_PASSWORD=$ENV_PAS" 
                    arguments:
#                      - -e
#                      - VMWARE_USER="afR1Jn+xAudF0/Nm2N2EG2N/baI/CDEvPQn+sBBr6SA="
#                      - VMWARE_PASSWORD="vYQVUN7yu95pKam/1zqY5Q=="'
#                      - --extra-vars "VMWARE_USER=$ENV_USR VMWARE_PASSWORD=$ENV_PAS"
      - Deploy-test-VM:
          clean_workspace: true
          jobs:
            Deploy-test-VM:          
              resources:
                - linux
              tasks:
                - exec:
                    command: ansible-playbook
                    arguments:
                      - deploy-test-vm.yaml
                      - --extra-vars "ESXI_USERNAME=$ENV_USR ESXI_PASSWORD=$ENV_PAS"
      - Final_Cleanup:
          clean_workspace: true
          jobs:
            rename_templates:
              resources:
                - linux          
              tasks:
                - exec:
                    command: ansible-playbook
                    arguments:
                      - rename-templates.yaml
                      - --extra-vars "ESXI_USERNAME=$ENV_USR ESXI_PASSWORD=$ENV_PAS"


