pipelines:
   template-patching-prod-2k12:
    secure_variables:
      ENV_USR: "3bhg4IGrgj5UHwrOniE6r8OQUT6c8ctQQkAbG4y487o="
      ENV_PAS: "NJqRv82x8/vlDDM2L+HDdg=="
    group: Windows-Template-Patching
    timer:
      spec: "0 0 3 ? * TUE,SAT"
      only_on_changes: no
    materials:
      infracode:
        git: git@githuben.intranet.mckinsey.com:himanshu-sharma-xft/template-patching-prod-2k12.git
        branch: master
        auto_update: true
        blacklist:
        - "README.md"
    stages:
      - Update-Template:
          clean_workspace: true
          jobs:
            Update-Template:          
              resources:
                - linux
              tasks:
                - exec:
                    command: ansible-playbook
                    arguments:
                      - final_code.yaml
                      - --extra-vars "esxi_username=$ENV_USR esxi_password=$ENV_PAS"
      - Deploy-test-VM:
          clean_workspace: true
          jobs:
            Deploy-test-VM:          
              resources:
                - linux
              tasks:
                - exec:
                    command: ansible-playbook
                    arguments:
                      - deploy-test-vm.yaml
                      - --extra-vars "ESXI_USERNAME=$ENV_USR ESXI_PASSWORD=$ENV_PAS"
      - Final_Cleanup:
          clean_workspace: true
          jobs:
            rename_templates:
              resources:
                - linux          
              tasks:
                - exec:
                    command: ansible-playbook
                    arguments:
                      - rename-templates.yaml
                      - --extra-vars "ESXI_USERNAME=$ENV_USR ESXI_PASSWORD=$ENV_PAS"


