pipelines:
   template-patching-prod-2k12:
    group: Windows-Template-Patching
    timer:
      spec: "0 0 3 ? * TUE,SAT"
      only_on_changes: no
    materials:
      infracode:
        git: git@githuben.intranet.mckinsey.com:himanshu-sharma-xft/template-patching-prod-2k12.git
        branch: master
        auto_update: true
        blacklist:
        - "README.md"
    stages:
      - Update-Template:
          clean_workspace: true
          jobs:
            Update-Template:          
              resources:
                - linux
              tasks:
                - exec:
                    command: ansible-playbook
                    arguments:
                      - final_code.yaml 
		      - --vault-password-file=/cicd-code/linux/vaultpasswd/vaultpasswd.txt
      - Deploy-test-VM:
          clean_workspace: true
          jobs:
            Deploy-test-VM:          
              resources:
                - linux
              tasks:
                - exec:
                    command: ansible-playbook
                    arguments:
                      - deploy-test-vm.yaml --vault-password-file=/cicd-code/linux/vaultpasswd/vaultpasswd.txt
      - Final_Cleanup:
          clean_workspace: true
          jobs:
            rename_templates:
              resources:
                - linux          
              tasks:
                - exec:
                    command: ansible-playbook
                    arguments:
                      - rename-templates.yaml --vault-password-file=/cicd-code/linux/vaultpasswd/vaultpasswd.txt


