pipelines:
   template-patching-prod-2k12:
#    secure_variables:
    environment_variables:
      ENV_USER: "{{SECRET:[Secret-vCenter][ENV_USR]}}"
#      ENV_USR: "{{SECRET:[Secret-vCenter][ENV_USR]}}"
      ENV_PASSWORD: "{{SECRET:[Secret-vCenter][ENV_PASS]}}"
    group: Windows-Template-Patching
    timer:
      spec: "0 0 3 ? * SAT"
      only_on_changes: no
    materials:
      infracode:
        git: git@githuben.intranet.mckinsey.com:himanshu-sharma-xft/template-patching-prod-2k12.git
        branch: master
        auto_update: true
        blacklist:
        - "README.md"
    stages:
      - Update-Template:
          clean_workspace: true
          jobs:
            Update-Template:          
              resources:
                - linux
              tasks:
                - exec:
                    command: ansible-playbook
                    arguments:
                      - final_code.yaml
                      - -e
                      - "VMWARE_USER=$ENV_USER VMWARE_PASSWORD=$ENV_PASSWORD"
#                      - --extra-vars "VMWARE_USER=$ENV_USR VMWARE_PASSWORD=$ENV_PAS"
      - Deploy-test-VM:
          clean_workspace: true
          jobs:
            Deploy-test-VM:          
              resources:
                - linux
              tasks:
                - exec:
                    command: ansible-playbook
                    arguments:
                      - deploy-test-vm.yaml
                      - --extra-vars "ESXI_USERNAME=$ENV_USR ESXI_PASSWORD=$ENV_PAS"
      - Final_Cleanup:
          clean_workspace: true
          jobs:
            rename_templates:
              resources:
                - linux          
              tasks:
                - exec:
                    command: ansible-playbook
                    arguments:
                      - rename-templates.yaml
                      - --extra-vars "ESXI_USERNAME=$ENV_USR ESXI_PASSWORD=$ENV_PAS"


