- name: Poweron VM
  gather_facts: no
  vars_files:
    - variable/credentials.yml
    - variable/variable.yml
  hosts: localhost
  tasks:
    - name: "Power OFF vm"
      vmware_guest:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ VMWARE_USER }}"
        password: "{{ VMWARE_PASSWORD }}"
        validate_certs: no
        datacenter: "{{ vmware_datacenter }}"
        state: poweredoff
        folder: "{{ vmware_folder }}"
        name: "{{ test_vm }}"
        is_template: False
